#!/bin/bash

# sysinfo_page - A script to produce an HTML file

# This is a "here script", an additional form of I/O redirection.
# It provides a way to include content that will be given to the standard input of a command
# $ sysinfo_page > sysinfo_page.html
# Environment variables are already set by the startup file

# No spaces between variable name and equal sign
title="System Information for"

cat <<- _EOF_

<html>
	<head>
		<title>$title $HOSTNAME</title>
	</head>

	<body>
		<h1>$HOSTNAME</h1>
	</body>
</html>

_EOF_

